version: "3.9"

services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: janu
      POSTGRES_DB: restaurant_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../..
      dockerfile: cloud/docker/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:janu@db:5432/restaurant_db
    depends_on:
      - db

  frontend:
    build:
      context: ../..
      dockerfile: cloud/docker/Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: